"""add device id to user

Revision ID: b3def762938a
Revises: 5405b78129b9
Create Date: 2025-08-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3def762938a'
down_revision = '5405b78129b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_user_device_id'), ['device_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_device_id'), type_='unique')
        batch_op.drop_column('device_id')
    # ### end Alembic commands ###
